fix: update configuration of pipeline

diff --git a/.github/workflows/staging.yml b/.github/workflows/staging.yml
--- a/.github/workflows/staging.yml
+++ b/.github/workflows/staging.yml
@@ -40,6 +40,12 @@ jobs:
 
       - name: Deploy & Restart PM2
         run: |
+          # cek apakah Secrets TARGET_DIR sudah diatur
+          if [ -z "${{ secrets.TARGET_DIR }}" ]; then
+            echo "Error: TARGET_DIR secret is not set."
+            exit 1
+          fi
+
           # Pastikan direktori target ada
           mkdir -p ${{ secrets.TARGET_DIR }}
           
